//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPortal.Web.LanguageResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationPortal.Web.LanguageResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AcquiredCount.
        /// </summary>
        public static string AcquiredCount
        {
            get
            {
                return ResourceManager.GetString("AcquiredCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All
        {
            get
            {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Education Portal.
        /// </summary>
        public static string ApplicationName
        {
            get
            {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles
        {
            get
            {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors
        {
            get
            {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available
        {
            get
            {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available Courses.
        /// </summary>
        public static string availableCourses
        {
            get
            {
                return ResourceManager.GetString("availableCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed
        {
            get
            {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed Courses.
        /// </summary>
        public static string completedCourses
        {
            get
            {
                return ResourceManager.GetString("completedCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Course Details.
        /// </summary>
        public static string CourseDetails
        {
            get
            {
                return ResourceManager.GetString("CourseDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses
        {
            get
            {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Course.
        /// </summary>
        public static string CreateCourse
        {
            get
            {
                return ResourceManager.GetString("CreateCourse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created
        {
            get
            {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy
        {
            get
            {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created Courses.
        /// </summary>
        public static string createdCourses
        {
            get
            {
                return ResourceManager.GetString("createdCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done
        {
            get
            {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration
        {
            get
            {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format
        {
            get
            {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Highest acquired level.
        /// </summary>
        public static string HighestAcquiredLevel
        {
            get
            {
                return ResourceManager.GetString("HighestAcquiredLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In-Progress.
        /// </summary>
        public static string InProgress
        {
            get
            {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In-Progress Courses.
        /// </summary>
        public static string inprogressCourses
        {
            get
            {
                return ResourceManager.GetString("inprogressCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level
        {
            get
            {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load
        {
            get
            {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout
        {
            get
            {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mark as Done.
        /// </summary>
        public static string MarkAsDone
        {
            get
            {
                return ResourceManager.GetString("MarkAsDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials
        {
            get
            {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New
        {
            get
            {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages
        {
            get
            {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile
        {
            get
            {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress
        {
            get
            {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publication Date.
        /// </summary>
        public static string PublicationDate
        {
            get
            {
                return ResourceManager.GetString("PublicationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        public static string Publications
        {
            get
            {
                return ResourceManager.GetString("Publications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publication Year.
        /// </summary>
        public static string PublicationYear
        {
            get
            {
                return ResourceManager.GetString("PublicationYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality
        {
            get
            {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registered Courses.
        /// </summary>
        public static string registeredCourses
        {
            get
            {
                return ResourceManager.GetString("registeredCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Link.
        /// </summary>
        public static string ResourceLink
        {
            get
            {
                return ResourceManager.GetString("ResourceLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Article.
        /// </summary>
        public static string SelectArticle
        {
            get
            {
                return ResourceManager.GetString("SelectArticle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Publication.
        /// </summary>
        public static string SelectPublication
        {
            get
            {
                return ResourceManager.GetString("SelectPublication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Skill.
        /// </summary>
        public static string SelectSkill
        {
            get
            {
                return ResourceManager.GetString("SelectSkill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Video.
        /// </summary>
        public static string SelectVideo
        {
            get
            {
                return ResourceManager.GetString("SelectVideo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Skill
        {
            get
            {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills
        {
            get
            {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos
        {
            get
            {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
    }
}
